# Generated by Django 3.0.8 on 2020-07-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePerson',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Actor_Actress', 'Actor_Actress'), ('Director', 'Director'), ('Producer', 'Producer')], max_length=15)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TypePerson',
                'verbose_name_plural': 'TypePersons',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=180)),
                ('firstname', models.CharField(max_length=180)),
                ('aliases', models.CharField(blank=True, max_length=80, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('typepersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='core.TypePerson')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['firstname'],
                'index_together': {('person_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('sipnosis', models.TextField(blank=True, null=True)),
                ('Release_Year', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('Horror', 'Horror'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('SciFi', 'SciFi'), ('Action', 'Action'), ('Period', 'Period')], max_length=10)),
                ('top', models.ImageField(blank=True, null=True, upload_to='movies')),
                ('state', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Actor_Actress', models.ManyToManyField(related_name='actor_actress', to='core.Person')),
                ('Director', models.ManyToManyField(related_name='director', to='core.Person')),
                ('Producer', models.ManyToManyField(related_name='producer', to='core.Person')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['title'],
                'index_together': {('movie_id', 'slug')},
            },
        ),
    ]
